function displayPoem(response){
    console.log("poem generated");
    new Typewriter("#poem", {
        strings: response.data.answer,
        autoStart: true,
        delay: 1,
        cursor: "",
      });
}




function generatePoem(event){
    event.preventDefault();
    
    let instructionsInput = document.querySelector("#user-instructions");
    let apiKey ="b2ftbed3f683eac832c6c0ec983o4a40";
    let prompt =`User instructions: Generate a English poem about flowers ${instructionsInput.value}`;
    let context ="You are a romantic poem expert and you love to write short poems. your mission is to generate a four line poem and separate each line with a <br>, also don't write html at all on the poem page.sign the poem saying generated by Emily's AI poem generator with a <strong> it should be italic. make sure to follow the user instructions";
    let apiUrl =`https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

    console.log("Generating poem");
    console.log(`Prompt: ${prompt}`);
    console.log(`Context: ${context}`);

    axios.get(apiUrl).then(displayPoem);

   

    
}

let poemFormElement = document.querySelector("#poem-generator-form");
poemFormElement.addEventListener("submit", generatePoem);